services:
  api:
    image: darenvv/ifc31c-iaw-vejarano-daren:vfinal
    container_name: api-bonsai
    restart: always
    networks:
      - bonsai-net

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - bonsai-net
    restart: always

networks:
  bonsai-net:

volumes:
  caddy_data:
  caddy_config: